version: 2.1

jobs:
  run-lint:
    docker:
      - image: python:3.7.3-stretch

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # run build
      - run:
          name: install dependencies
          command: |
            python3 -m venv capstoneenv
            . capstoneenv/bin/activate
            make install

      # run lint
      - run:
          name: run lint
          command: |
            . capstoneenv/bin/activate
            make lint

      - save_cache:
          paths:
            - ./capstoneenv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

workflows:
  default:
    jobs:
      - run-lint