apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  namespace: default
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: capstone-app
  template:
    metadata:
      labels:
        app: capstone-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: capstone-app
          image: anshuljain1706/capstone:latest
          ports:
            - name: http
              containerPort: 80
          imagePullPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux
